version: 0.4.{build}

branches:
  only:
  - master 

clone_depth: 1

before_build:
- cmd: nuget restore

build_script:
    - set path=%path%;C:\Program Files (x86)\Mono\bin
    - xbuild /p:Configuration=Release Crow.sln 

#build: off

build:

#  project: Crow.sln

  verbosity: normal
