// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;


namespace go {
    
    public partial class testBorder : Border {
        public testBorder() {
            this.BorderWidth = 5;
            this.Width = 200;
            this.Height = 200;
            this.CornerRadius = 20;
            this.Margin = 0;
            this.Background = go.Color.Mantis;
            this.SetChild(new go.GraphicObject());
            this.Child.CornerRadius = 0;
            this.Child.Background = go.Color.CornflowerBlue;
            this.Child.Height = 100;
            this.Child.Width = 100;
        }
    }
}
