// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Rsvg {

	using System;

	public delegate void SizeFunc(out int width, out int height);

}
